# Generated by Django 4.2.1 on 2023-05-12 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_cart_quantity_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
