# Generated by Django 4.2.1 on 2023-05-15 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0007_remove_cart_books_alter_orderitem_book_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_price',
        ),
    ]
